#define RGBLIGHT_SPLIT

#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 70
#define MOUSEKEY_TIME_TO_MAX 3

#define MUSIC_MASK (keycode != KC_NO)
#define MIDI_ADVANCED

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define TAPPING_FORCE_HOLD
